// This file can be replaced during build by using the `fileReplacements` array.
// `ng build --prod` replaces `environment.ts` with `environment.prod.ts`.
// The list of file replacements can be found in `angular.json`.

export const environment = {
  firebase: {
    projectId: 'movies-votes-91b1f',
    locationId: 'us-central1',
    authDomain: 'localhost:5001',
  },
  production: false,
};

export const movies = {
  page: 1,
  results: [
    {
      adult: false,
      backdrop_path: '/p1F51Lvj3sMopG948F5HsBbl43C.jpg',
      genre_ids: [28, 12, 14],
      id: 616037,
      original_language: 'en',
      original_title: 'Thor: Love and Thunder',
      overview:
        'Thor parte em uma jornada diferente de tudo que já enfrentou – uma busca pela paz interior. Mas sua aposentadoria é interrompida por um assassino galáctico conhecido como Gorr, o Carniceiro de Deus, que busca a extinção dos deuses. Para combater a ameaça, Thor pede a ajuda do Rei Valquíria, Korg e da ex-namorada Jane Foster, que – para surpresa de Thor – inexplicavelmente empunha seu martelo mágico, Mjolnir, como o Poderoso Thor. Juntos, eles embarcam em uma angustiante aventura cósmica para descobrir o mistério da vingança do God Butcher e detê-lo antes que seja tarde demais.',
      popularity: 8625.547,
      poster_path: '/6OEBp0Gqv6DsOgi8diPUslT2kbA.jpg',
      release_date: '2022-07-06',
      title: 'Thor: Amor e Trovão',
      video: false,
      vote_average: 6.8,
      vote_count: 1774,
    },
    {
      adult: false,
      backdrop_path: '/7bhvI1tM7JBmqP8HSevIsebSBbh.jpg',
      genre_ids: [12, 28, 878],
      id: 507086,
      original_language: 'en',
      original_title: 'Jurassic World Dominion',
      overview:
        'Quatro anos após a destruição da Ilha Nublar, os dinossauros agora vivem – e caçam – ao lado de humanos em todo o mundo. Esse frágil equilíbrio remodelará o futuro e determinará, de uma vez por todas, se os seres humanos continuarão sendo os principais predadores em um planeta que agora compartilham com as criaturas mais temíveis da história.',
      popularity: 4799.187,
      poster_path: '/7qeiCNSmzrkcEyIWi8sIcsjrOyW.jpg',
      release_date: '2022-06-01',
      title: 'Jurassic World: Domínio',
      video: false,
      vote_average: 7.1,
      vote_count: 2643,
    },
    {
      adult: false,
      backdrop_path: '/nmGWzTLMXy9x7mKd8NKPLmHtWGa.jpg',
      genre_ids: [10751, 16, 12, 35, 14],
      id: 438148,
      original_language: 'en',
      original_title: 'Minions: The Rise of Gru',
      overview:
        'A continuação das aventuras dos Minions, sempre em busca de um líder tirânico. Dessa vez, eles ajudam um Gru ainda criança, descobrindo como ser vilão.',
      popularity: 4511.803,
      poster_path: '/tzFAboMUGJKoPQEtlxfxbbYsSWa.jpg',
      release_date: '2022-06-29',
      title: 'Minions 2: A Origem de Gru',
      video: false,
      vote_average: 7.8,
      vote_count: 1199,
    },
    {
      adult: false,
      backdrop_path: '/7ZO9yoEU2fAHKhmJWfAc2QIPWJg.jpg',
      genre_ids: [28, 53, 878, 27],
      id: 766507,
      original_language: 'en',
      original_title: 'Prey',
      overview:
        'Ambientado no mundo da Nação Comanche no início de 1700, "O Predador: A Caçada" é a história não contada de uma jovem guerreira altamente qualificada, desesperada para proteger seu povo do perigo iminente. Ela persegue e finalmente confronta sua presa, que acaba sendo um predador alienígena altamente evoluído com um arsenal tecnologicamente avançado, resultando em um confronto brutal e aterrorizante entre os adversários.',
      popularity: 4477.547,
      poster_path: '/g7Ii9sYAFG96W7cvMQ4zXq39RJ5.jpg',
      release_date: '2022-08-02',
      title: 'O Predador: A Caçada',
      video: false,
      vote_average: 8.2,
      vote_count: 1711,
    },
    {
      adult: false,
      backdrop_path: '/odJ4hx6g6vBt4lBWKFD1tI8WS4x.jpg',
      genre_ids: [28, 18],
      id: 361743,
      original_language: 'en',
      original_title: 'Top Gun: Maverick',
      overview:
        'Depois de mais de 30 anos de serviço como um dos principais aviadores da Marinha, Pete "Maverick" Mitchell está de volta, rompendo os limites como um piloto de testes corajoso. No mundo contemporâneo das guerras tecnológicas, Maverick enfrenta drones e prova que o fator humano ainda é essencial.',
      popularity: 4227.421,
      poster_path: '/jeGvNOVMs5QIU1VaoGvnd3gSv0G.jpg',
      release_date: '2022-05-24',
      title: 'Top Gun: Maverick',
      video: false,
      vote_average: 8.3,
      vote_count: 1859,
    },
    {
      adult: false,
      backdrop_path: '/AfvIjhDu9p64jKcmohS4hsPG95Q.jpg',
      genre_ids: [27, 53],
      id: 756999,
      original_language: 'en',
      original_title: 'The Black Phone',
      overview:
        'Finney Shaw, um menino tímido, mas inteligente, de 13 anos, é sequestrado por um assassino sádico e preso em um porão à prova de som, onde gritar é de pouca utilidade. Quando um telefone desconectado na parede começa a tocar, Finney descobre que pode ouvir as vozes das vítimas anteriores do assassino. E eles estão determinados a garantir que o que aconteceu com eles não aconteça com Finney.',
      popularity: 2941.242,
      poster_path: '/p9ZUzCyy9wRTDuuQexkQ78R2BgF.jpg',
      release_date: '2022-06-22',
      title: 'O Telefone Preto',
      video: false,
      vote_average: 8,
      vote_count: 1698,
    },
    {
      adult: false,
      backdrop_path: '/nW5fUbldp1DYf2uQ3zJTUdachOu.jpg',
      genre_ids: [16, 878, 12, 28, 10751],
      id: 718789,
      original_language: 'en',
      original_title: 'Lightyear',
      overview:
        'A aventura de ação e ficção científica apresenta a história de origem definitiva de Buzz Lightyear - o herói que inspirou o brinquedo - apresentando o lendário Space Ranger que conquistaria gerações de fãs.',
      popularity: 2442.953,
      poster_path: '/wDnKL1eBkSkGGBK6WoQxZZVDCHU.jpg',
      release_date: '2022-06-15',
      title: 'Lightyear',
      video: false,
      vote_average: 7.3,
      vote_count: 1521,
    },
    {
      adult: false,
      backdrop_path: '/wcKFYIiVDvRURrzglV9kGu7fpfY.jpg',
      genre_ids: [14, 28, 12],
      id: 453395,
      original_language: 'en',
      original_title: 'Doctor Strange in the Multiverse of Madness',
      overview:
        'Doutor Estranho, com a ajuda de aliados místicos antigos e novos, atravessa as perigosas realidades alternativas e alucinantes do Multiverso para enfrentar um novo adversário misterioso.',
      popularity: 2524.891,
      poster_path: '/boIgXXUhw5O3oVkhXsE6SJZkmYo.jpg',
      release_date: '2022-05-04',
      title: 'Doutor Estranho no Multiverso da Loucura',
      video: false,
      vote_average: 7.5,
      vote_count: 5170,
    },
    {
      adult: false,
      backdrop_path: '/27Mj3rFYP3xqFy7lnz17vEd8Ms.jpg',
      genre_ids: [28, 53],
      id: 725201,
      original_language: 'en',
      original_title: 'The Gray Man',
      overview:
        'Na Europa, um agente da CIA que se tornou assassino tenta escapar de forças misteriosas enquanto tenta salvar a vida das filhas que não sabem que ele existe.',
      popularity: 2449.294,
      poster_path: '/1f10KUKW7KyNt8bF8NHmwbBQ9fs.jpg',
      release_date: '2022-07-13',
      title: 'Agente Oculto',
      video: false,
      vote_average: 7.1,
      vote_count: 1409,
    },
    {
      adult: false,
      backdrop_path: '/k5SYb9AM0x4IGVxG8fYEEH4wK1I.jpg',
      genre_ids: [10749, 18],
      id: 762975,
      original_language: 'en',
      original_title: 'Purple Hearts',
      overview:
        'Uma música e um militar prestes a ir para a guerra se casam por conveniência. Mas uma tragédia transforma esse relacionamento de fachada em realidade.',
      popularity: 2000.331,
      poster_path: '/ncBNV5G7EBLPK2X6cO55krYrPRw.jpg',
      release_date: '2022-07-29',
      title: 'Continência ao Amor',
      video: false,
      vote_average: 8.6,
      vote_count: 917,
    },
    {
      adult: false,
      backdrop_path: '/5PnypKiSj2efSPqThNjTXz8jwOg.jpg',
      genre_ids: [14, 28],
      id: 759175,
      original_language: 'en',
      original_title: 'The Princess',
      overview:
        'Quando uma princesa bela e determinada se recusa a se casar com o cruel sociopata para quem está prometida, ela é sequestrada e trancada em uma torre remota no castelo de seu pai. Com seu pretendente desprezado e vingativo querendo tomar o trono, a princesa deve proteger sua família e salvar o reino, custe o que custar.',
      popularity: 1721.623,
      poster_path: '/wNQlyv4S1j0pnsMe48ARAgI7Ncp.jpg',
      release_date: '2022-06-16',
      title: 'A Princesa',
      video: false,
      vote_average: 7,
      vote_count: 404,
    },
    {
      adult: false,
      backdrop_path: '/l99dylTOAMkwKSr54X5ytiEtnLA.jpg',
      genre_ids: [14, 12, 28],
      id: 919355,
      original_language: 'en',
      original_title: 'Dragon Knight',
      overview:
        'Quando uma força malévola toma conta dos reinos de Agonos, um cavaleiro solitário deve embarcar numa perigosa busca para encontrar o último dragão e salvar o mundo deste grande e crescente mal.',
      popularity: 1728.352,
      poster_path: '/7xgLuY6cLcJZDw629gCOKzN7Xxv.jpg',
      release_date: '2022-03-21',
      title: 'O Último Dragão',
      video: false,
      vote_average: 6.9,
      vote_count: 16,
    },
    {
      adult: false,
      backdrop_path: '/jazlkwXfw4KdF6fVTRsolOvRCmu.jpg',
      genre_ids: [53],
      id: 924482,
      original_language: 'en',
      original_title: 'The Ledge',
      overview:
        'Uma montanhista presa na encosta de uma montanha precisa lutar contra quatro assassinos que estão em uma saliência seis metros acima dela.',
      popularity: 1609.046,
      poster_path: '/mKFT6Q7PjrRLYuPLfmH4WLCXOiD.jpg',
      release_date: '2022-02-18',
      title: 'Tensão nas Alturas',
      video: false,
      vote_average: 6.3,
      vote_count: 76,
    },
    {
      adult: false,
      backdrop_path: '/ocUp7DJBIc8VJgLEw1prcyK1dYv.jpg',
      genre_ids: [28, 12, 878],
      id: 634649,
      original_language: 'en',
      original_title: 'Spider-Man: No Way Home',
      overview:
        'Peter Parker é desmascarado e não consegue mais separar sua vida normal dos grandes riscos de ser um super-herói. Quando ele pede ajuda ao Doutor Estranho, os riscos se tornam ainda mais perigosos, e o forçam a descobrir o que realmente significa ser o Homem-Aranha...',
      popularity: 1502.371,
      poster_path: '/fVzXp3NwovUlLe7fvoRynCmBPNc.jpg',
      release_date: '2021-12-15',
      title: 'Homem-Aranha: Sem Volta Para Casa',
      video: false,
      vote_average: 8,
      vote_count: 14581,
    },
    {
      adult: false,
      backdrop_path: '/4dNv1W1KMSLdYGz0tCEaynF0E4Q.jpg',
      genre_ids: [28, 53, 80],
      id: 854467,
      original_language: 'en',
      original_title: 'Indemnity',
      overview:
        'O mundo de um ex-bombeiro da Cidade do Cabo é abalado quando ele acorda ao lado do corpo de sua esposa, sem memória do que aconteceu e todas as evidências apontam-lhe como o assassino.',
      popularity: 1525.429,
      poster_path: '/uPrMoy75cIBQSnIX947CakeZ6Nx.jpg',
      release_date: '2022-02-11',
      title: 'Sem Culpa',
      video: false,
      vote_average: 6.9,
      vote_count: 48,
    },
    {
      adult: false,
      backdrop_path: '/obTdaJ22RNFi3fmzUVT5eWOFsOe.jpg',
      genre_ids: [53, 80],
      id: 728366,
      original_language: 'en',
      original_title: 'Borrego',
      overview:
        'Sinopse. Borrego segue uma jovem botânica que se muda para uma pequena cidade no deserto para estudar uma espécie de planta invasora. Ela deve lutar por sua sobrevivência quando é sequestrada por uma mula de drogas inexperiente após seu avião ultraleve cair no deserto.',
      popularity: 1423.389,
      poster_path: '/iNSa1kwVsOsfAHwopMLM7PnrDhU.jpg',
      release_date: '2022-01-14',
      title: 'Borrego - Saia Do Caminho',
      video: false,
      vote_average: 6,
      vote_count: 36,
    },
    {
      adult: false,
      backdrop_path: '/ftGzl2GCyko61Qp161bQElN2Uzd.jpg',
      genre_ids: [28, 53],
      id: 961484,
      original_language: 'en',
      original_title: 'Last Seen Alive',
      overview:
        'Will Spann está dirigindo com sua futura ex-esposa Lisa para a casa de seus pais quando ela desaparece misteriosamente sem deixar rastros durante uma parada em um posto de gasolina. Will envolve a polícia local e os pais de Lisa em uma tentativa desesperada de encontrá-la, mas com o passar do tempo e a suspeita cair sobre ele, ele deve resolver o assunto com suas próprias mãos, investigando o submundo criminoso da cidade enquanto foge das autoridades em um corrida contra o tempo para encontrar Lisa.',
      popularity: 1487.086,
      poster_path: '/mOl6OY1xQCLqy0FbpMyBSReS8IG.jpg',
      release_date: '2022-05-19',
      title: 'Caça Implacável',
      video: false,
      vote_average: 6.6,
      vote_count: 205,
    },
    {
      adult: false,
      backdrop_path: '/rLo9T9jEg67UZPq3midjLnTUYYi.jpg',
      genre_ids: [10402, 18, 36],
      id: 614934,
      original_language: 'en',
      original_title: 'Elvis',
      overview:
        'A história de vida de Elvis Presley vista através do relacionamento complicado com seu empresário enigmático, o coronel Tom Parker.',
      popularity: 1449.552,
      poster_path: '/dmMyGIBsvUrfDNV8bWVEN8MidbG.jpg',
      release_date: '2022-06-22',
      title: 'Elvis',
      video: false,
      vote_average: 7.9,
      vote_count: 819,
    },
    {
      adult: false,
      backdrop_path: '/8wwXPG22aNMpPGuXnfm3galoxbI.jpg',
      genre_ids: [28, 12, 10751, 35],
      id: 675353,
      original_language: 'en',
      original_title: 'Sonic the Hedgehog 2',
      overview:
        'Depois de se estabelecer em Green Hills, Sonic está pronto para mais liberdade e deixar sua marca como um herói, e Tom e Maddie concordam em deixá-lo em casa enquanto vão de férias. Mas, assim que eles se foram, Dr. Robotnik volta, desta vez com um novo parceiro, Knuckles, em busca de uma esmeralda que tem o poder de construir e destruir civilizações. Sonic se une a um novo companheiro, Tails, e juntos eles embarcam em uma jornada para encontrar a esmeralda antes que ela caia nas mãos erradas.',
      popularity: 1300.566,
      poster_path: '/f4SvCKIUrC2cDR7Xo4k1kaGAqQ2.jpg',
      release_date: '2022-03-30',
      title: 'Sonic 2: O Filme',
      video: false,
      vote_average: 7.7,
      vote_count: 2735,
    },
    {
      adult: false,
      backdrop_path: '/t9K8ycUBCplWiICDOKRNRYcEH9e.jpg',
      genre_ids: [16, 28, 14],
      id: 810693,
      original_language: 'ja',
      original_title: '劇場版 呪術廻戦 0',
      overview:
        'O jovem Yuta Okkotsu ganha o controle de um espírito extremamente poderoso, então um grupo de feiticeiros o matriculam na Tokyo Prefectural Jujutsu High School, para ajudá-lo a controlar esse poder e também para ficar de olho nele.',
      popularity: 1289.724,
      poster_path: '/m8nyqnn2K7WzxcAKzCxPxuX7Yd1.jpg',
      release_date: '2021-12-24',
      title: 'Jujutsu Kaisen 0: O Filme',
      video: false,
      vote_average: 7.8,
      vote_count: 243,
    },
  ],
  total_pages: 34681,
  total_results: 693613,
};

/*
 * For easier debugging in development mode, you can import the following file
 * to ignore zone related error stack frames such as `zone.run`, `zoneDelegate.invokeTask`.
 *
 * This import should be commented out in production mode because it will have a negative impact
 * on performance if an error is thrown.
 */
// import 'zone.js/dist/zone-error';  // Included with Angular CLI.
